CREATE DATABASE softuni_library;

USE softuni_library;


CREATE TABLE `users` (
	`USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USERNAME` VARCHAR(255) NOT NULL,
	`PASSWORD` VARCHAR(255) NOT NULL,
	`FULL_NAME` VARCHAR(255) NOT NULL,
	`BORN_ON` DATE NOT NULL,
	PRIMARY KEY (`USER_ID`),
	UNIQUE INDEX `USERNAME` (`USERNAME`)
)
ENGINE=InnoDB
;

CREATE TABLE `genres` (
	`GENRE_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(50) NOT NULL DEFAULT '0',
	PRIMARY KEY (`GENRE_ID`)
)
ENGINE=InnoDB
;

CREATE TABLE `books` (
	`BOOK_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`TITLE` VARCHAR(50) NOT NULL,
	`AUTHOR` VARCHAR(50) NOT NULL,
	`DESCRIPTION` TEXT NULL,
	`IMAGE` VARCHAR(255) NULL DEFAULT NULL,
	`GENRE_ID` INT(11) NOT NULL,
	`USER_ID` INT(11) NOT NULL,
	`ADDED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`BOOK_ID`),
	INDEX `FK_books_genres` (`GENRE_ID`),
	INDEX `FK_books_users` (`USER_ID`),
	CONSTRAINT `FK_books_genres` FOREIGN KEY (`GENRE_ID`) REFERENCES `genres` (`GENRE_ID`),
	CONSTRAINT `FK_books_users` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


INSERT INTO `softuni_library`.`genres` (`NAME`) VALUES ('Drama');
INSERT INTO `softuni_library`.`genres` (`NAME`) VALUES ('Educational');
INSERT INTO `softuni_library`.`genres` (`NAME`) VALUES ('Adventure');